// BLUE SET (#009-#016) - Food - EPIC
import type { Card } from "../cardData";

export const BLUE_CARDS: Card[] = [
  {
    id: "#009",
    emoji: "🍔",
    color: "blue",
    nameTH: "เบอร์เกอร์พลัง",
    nameEN: "Power Burger",
    stats: { mind: 20, body: 35, spirit: 30 },
    rarity: "epic",
    lore: [
      "เบอร์เกอร์ที่นักเรียนทำขาด",
      "กินแล้วมีแรงต่อไป",
      '"เติมพลังให้สมอง"',
    ],
    ability: "เพิ่มพลังความอดทน อดทนต่อความหิวได้นานขึ้น",
  },
  {
    id: "#010",
    emoji: "🍕",
    color: "blue",
    nameTH: "พิซซ่าแห่งความสุข",
    nameEN: "Happiness Pizza",
    stats: { mind: 25, body: 30, spirit: 50 },
    rarity: "epic",
    lore: [
      "พิซซ่าที่แบ่งปันความสุข",
      "ทำให้อ่านหนังสือเพลิดเพลิน",
      '"เรียนเป็น เล่นก็เป็น"',
    ],
    ability: "เพิ่มความสุขในการเรียน อ่านได้นานขึ้นโดยไม่เบื่อ",
  },
  {
    id: "#011",
    emoji: "🍜",
    color: "blue",
    nameTH: "บะหมี่กึ่งสำเร็จแห่งการทบทวน",
    nameEN: "Review Noodle",
    stats: { mind: 40, body: 35, spirit: 35 },
    rarity: "epic",
    lore: [
      "บะหมี่ที่ช่วยทบทวนบทเรียน",
      "เส้นบะหมี่แทนความเชื่อมโยง",
      '"ทบทวนไป เรียนรู้ไป"',
    ],
    ability: "ช่วยทบทวนบทเรียน จำเนื้อหาได้ดีขึ้น 30%",
  },
  {
    id: "#012",
    emoji: "🍣",
    color: "blue",
    nameTH: "ซูชิแห่งความเรียบเรียง",
    nameEN: "Organized Sushi",
    stats: { mind: 50, body: 30, spirit: 40 },
    rarity: "epic",
    lore: [
      "ซูชิที่เรียงงามเป็นระเบียบ",
      "สอนให้รู้จักการจัดระเบียบ",
      '"เรียบเรียงความคิด เรียบเรียงชีวิต"',
    ],
    ability: "ช่วยจัดระเบียบความคิด เขียนคำตอบเป็นระเบียบ",
  },
  {
    id: "#013",
    emoji: "🍦",
    color: "blue",
    nameTH: "ไอศกรีมเย็นใจ",
    nameEN: "Cool Mind Ice Cream",
    stats: { mind: 35, body: 25, spirit: 55 },
    rarity: "epic",
    lore: [
      "ไอศกรีมที่เย็นสมอง",
      "ช่วยให้คิดเย็นๆ เวลาทำข้อสอบ",
      '"เย็นใจ เข้มแข็ง"',
    ],
    ability: "สงบสมอง ลดความตึงเครียด เวลาทำข้อสอบได้ดีขึ้น",
  },
  {
    id: "#014",
    emoji: "🍩",
    color: "blue",
    nameTH: "โดนัทแหวนแห่งสมาธิ",
    nameEN: "Focus Donut",
    stats: { mind: 55, body: 30, spirit: 40 },
    rarity: "epic",
    lore: [
      "โดนัทรูปกลมวงกลม",
      "เหมือนสมาธิที่ไม่หลุดวง",
      '"มองแต่ในรู ไม่มีสิ่งรบกวน"',
    ],
    ability: "เพิ่มสมาธิระดับสูง อ่านต่อเนื่องได้ 60 นาที",
  },
  {
    id: "#015",
    emoji: "🍰",
    color: "blue",
    nameTH: "เค้กแห่งการเฉลิมฉลอง",
    nameEN: "Celebration Cake",
    stats: { mind: 45, body: 40, spirit: 65 },
    rarity: "epic",
    lore: [
      "เค้กที่เฉลิมฉลองความสำเร็จ",
      "ทุกครั้งที่ผ่านด่าน",
      "จะได้ทานเค้กชิ้นนี้",
      '"เฉลิมฉลองทุกความสำเร็จ"',
    ],
    ability: "เฉลิมฉลองความสำเร็จ เพิ่มความมั่นใจ โชคดีในการสอบ",
  },
  {
    id: "#016",
    emoji: "🧁",
    color: "blue",
    nameTH: "คัพเค้กนำโชค",
    nameEN: "Lucky Cupcake",
    stats: { mind: 30, body: 25, spirit: 75 },
    rarity: "epic",
    lore: [
      "คัพเค้กตัวน้อยที่มาพร้อมโชค",
      "ใครทานจะเจอเรื่องดี",
      '"โชคจะมาเมื่อเตรียมพร้อม"',
    ],
    ability: "เพิ่มโชคลาภ เจอข้อสอบที่ถนัด 50%",
  },
];
