// GRAY SET (#033-#040) - Weather - COMMON
import type { Card } from "../cardData";

export const GRAY_CARDS: Card[] = [
  {
    id: "#033",
    emoji: "☀️",
    color: "gray",
    nameTH: "ดวงอาทิตย์แห่งปัญญา",
    nameEN: "Sun of Wisdom",
    stats: { mind: 99, body: 95, spirit: 95 },
    rarity: "common",
    lore: [
      '"ในวันที่มืดมนที่สุด',
      "ดวงอาทิตย์ลูกนี้ลงมา",
      "มอบแสงสว่างให้ผู้ที่ศรัทธา",
      "นักเรียนผู้นั้นได้กลายเป็น",
      'ผู้สอบผ่านที่ยิ่งใหญ่ที่สุด"',
    ],
    ability: "สว่างไสว ความจำอมตะ โชคชะตา ครองความสำเร็จ",
  },
  {
    id: "#034",
    emoji: "🌧️",
    color: "gray",
    nameTH: "ฝนแห่งการเรียนรู้",
    nameEN: "Learning Rain",
    stats: { mind: 50, body: 60, spirit: 40 },
    rarity: "common",
    lore: [
      "ฝนที่ตกลงมาอย่างสม่ำเสมอ",
      "ช่วยให้ต้นไม้แห่งความรู้เติบโต",
      '"ฝนตก ต้นไม้เติบโต"',
    ],
    ability: "สม่ำเสมอ อ่านหนังสือเป็นประจำ เรียนรู้ได้ทุกวัน",
  },
  {
    id: "#035",
    emoji: "⛈️",
    color: "gray",
    nameTH: "พายุฟ้าแห่งความรู้",
    nameEN: "Knowledge Thunder",
    stats: { mind: 70, body: 45, spirit: 55 },
    rarity: "common",
    lore: [
      "พายุที่พัดผ่าน",
      "พาความรู้มาสู่ผู้ที่รอคอย",
      '"พายุผ่านไป ความรู้ยังคง"',
    ],
    ability: "ความรู้เข้าถึงเร็ว จำเนื้อหาได้ทันที",
  },
  {
    id: "#036",
    emoji: "❄️",
    color: "gray",
    nameTH: "หิมะเยือกแข็งแห่งสมาธิ",
    nameEN: "Focus Ice",
    stats: { mind: 85, body: 40, spirit: 50 },
    rarity: "common",
    lore: ["หิมะที่เยือกแข็ง", "สอนให้สงบนิ่ง", '"เยือกแข็ง เป็นระเบียบ"'],
    ability: "สงบสติอารมณ์ระดับสูง สมาธิแม่นยำ ลดความกลัว",
  },
  {
    id: "#037",
    emoji: "🌦️️",
    color: "gray",
    nameTH: "ฝนสาดแดดส่องแห่งความหวัง",
    nameEN: "Hope Weather",
    stats: { mind: 45, body: 35, spirit: 70 },
    rarity: "common",
    lore: [
      "ฝนสาด แดดส่อง",
      "เหมือนชีวิตที่มีทั้งดีและร้าย",
      '"หลังฝนฟ้า จะเจอแดดส่อง"',
    ],
    ability: "มองโลกในแง่ดี ฟื้นหวังเมื่อท้อ",
  },
  {
    id: "#038",
    emoji: "☃️",
    color: "gray",
    nameTH: "หิมะคนแห่งความเย็นใจ",
    nameEN: "Cool Mind Snowman",
    stats: { mind: 55, body: 35, spirit: 45 },
    rarity: "common",
    lore: ["หิมะคนที่ยืนอยู่ในหนาว", "สอนให้เย็นใจ", '"เย็นใจ ไม่ร้อนรุ่ม"'],
    ability: "เย็นใจ ไม่ตื่นเต้นเวลาสอบ",
  },
  {
    id: "#039",
    emoji: "🌖",
    color: "gray",
    nameTH: "พระจันทร์แห่งการทบทวน",
    nameEN: "Review Moon",
    stats: { mind: 65, body: 50, spirit: 45 },
    rarity: "common",
    lore: [
      "พระจันทร์ที่ส่องแสงในคืนมืด",
      "ช่วยให้ทบทวนได้",
      '"แสงจันทร์ ส่องทาง"',
    ],
    ability: "ทบทวนในค่ำคืน จำได้ดีขึ้น 50%",
  },
  {
    id: "#040",
    emoji: "⛅️",
    color: "gray",
    nameTH: "เมฆมุมเห็นฟ้า",
    nameEN: "Clear Sky Cloud",
    stats: { mind: 75, body: 45, spirit: 55 },
    rarity: "common",
    lore: [
      "เมฆที่ระบายให้ท้องฟ้าโล่ง",
      "เหมือนความคิดที่ชัดเจน",
      '"ท้องฟ้าโล่ง ความคิดโล่ง"',
      '"เห็นทาง ไปถึงฝัน"',
    ],
    ability: "มองเห็นภาพรวม ความคิดสร้างสรรค์ แก้ปัญหาได้อย่างลงตัว",
  },
];
