// GREEN SET (#017-#024) - Animals - RARE
import type { Card } from "../cardData";

export const GREEN_CARDS: Card[] = [
  {
    id: "#017",
    emoji: "🐱",
    color: "green",
    nameTH: "เจ้าเหมียวนำโชค",
    nameEN: "Lucky Cat",
    stats: { mind: 40, body: 35, spirit: 70 },
    rarity: "rare",
    lore: [
      "แมวที่ช่วยนักเรียนผ่าน",
      "ช่วงเวลายากลำบากที่สุด",
      "เมื่อนักเรียนกำลังจะท้อ",
      "เจ้าเหมียวปรากฏตัวขึ้น",
      '"เธอจะผ่านไปได้แน่นอน"',
    ],
    ability: "เจอข้อสอบที่ถนัด โชคดีในการสอบ",
  },
  {
    id: "#018",
    emoji: "🐶",
    color: "green",
    nameTH: "เพื่อนตรึ้จซื่อสัตย์",
    nameEN: "Loyal Friend",
    stats: { mind: 35, body: 45, spirit: 45 },
    rarity: "rare",
    lore: [
      "เพื่อนตัวน้อยที่อยู่ข้างกาย",
      "เวลาอ่านหนังสองไม่เหงา",
      '"มิตรภาพคือยาธรรมชาติ"',
    ],
    ability: "ลดความเหงาจากการอ่านโดดลำพัง เพิ่มความมุ่งมั่น",
  },
  {
    id: "#019",
    emoji: "🐰",
    color: "green",
    nameTH: "กระต่ายกระโดดความรู้",
    nameEN: "Knowledge Rabbit",
    stats: { mind: 45, body: 30, spirit: 55 },
    rarity: "rare",
    lore: [
      "กระต่ายกระโดดไปมา",
      "เรียนรู้อะไรไวมาก",
      '"กระโดดข้ามความยากลำบาก"',
    ],
    ability: "เรียนรู้เร็ว จำเนื้อหาใหม่ได้เร็ว 40%",
  },
  {
    id: "#020",
    emoji: "🦊",
    color: "green",
    nameTH: "สุนัขจิ้งจอกแห่งปัญญา",
    nameEN: "Wisdom Fox",
    stats: { mind: 60, body: 35, spirit: 50 },
    rarity: "rare",
    lore: [
      "สุนัขจิ้งจอกผู้มีปัญญา",
      "สอนให้คิดหลากหลาย",
      "มองเห็นสิ่งที่คนมองไม่เห็น",
      '"ปัญญาอยู่ที่ไหน ก็เอามาได้"',
    ],
    ability: "เพิ่มทักษะคิดวิเคราะห์ แก้โจทย์ปัญหาได้อย่างชาญฉลาด",
  },
  {
    id: "#021",
    emoji: "🐻",
    color: "green",
    nameTH: "หมีพันธุ์แกร่ง",
    nameEN: "Strong Bear",
    stats: { mind: 40, body: 70, spirit: 35 },
    rarity: "rare",
    lore: ["หมีผู้แข็งแกร่ง", "ทนทานต่อทุกสิ่ง", '"ความแข็งแกร่งคนละครึ่ง"'],
    ability: "เพิ่มความแข็งแกร่ง อ่านได้นานมาก โดยไม่เพลีย",
  },
  {
    id: "#022",
    emoji: "🐼",
    color: "green",
    nameTH: "แพนด้าสงบสติอารมณ์",
    nameEN: "Calm Panda",
    stats: { mind: 50, body: 40, spirit: 45 },
    rarity: "rare",
    lore: [
      "แพนด้าที่กินแต่ใบไผ่",
      "สอนให้สุขุม นิ่ง สงบ",
      '"สงบเป็น สุขุมเป็น"',
    ],
    ability: "สงบสติอารมณ์ ลดความตึงเครียด สอบได้ดีขึ้น",
  },
  {
    id: "#023",
    emoji: "🐨",
    color: "green",
    nameTH: "โคอาล่าหลับในความรู้",
    nameEN: "Knowledge Sleeper",
    stats: { mind: 55, body: 55, spirit: 40 },
    rarity: "rare",
    lore: [
      "โคอาล่าที่หลับตลอดเวลา",
      "แต่เวลาตื่นก็จำได้ทุกอย่าง",
      '"บางครั้ง การพักก็คือการเรียน"',
    ],
    ability: "เรียนรู้ขณะหลับ จำเนื้อหาได้ดีขึ้นจากการพักผ่อน",
  },
  {
    id: "#024",
    emoji: "🐯",
    color: "green",
    nameTH: "เสือนักสู้",
    nameEN: "Fighting Tiger",
    stats: { mind: 65, body: 50, spirit: 60 },
    rarity: "rare",
    lore: [
      "เสือผู้ไม่ยอมแพ้",
      "สอนให้ต่อสู้กับความยากลำบาก",
      '"นักสู้ตัวจริง ไม่ยอมแพ้"',
    ],
    ability: "เพิ่มความมุ่งมั่น ฝ่าฟันอุปสรรค ทำข้อสอบยากให้ได้",
  },
];
