// YELLOW SET (#025-#032) - Fruits - UNCOMMON
import type { Card } from "../cardData";

export const YELLOW_CARDS: Card[] = [
  {
    id: "#025",
    emoji: "🍎",
    color: "yellow",
    nameTH: "ส้มสมบูรณ์",
    nameEN: "Mandarin of Focus",
    stats: { mind: 45, body: 30, spirit: 35 },
    rarity: "uncommon",
    lore: [
      "ในคืนที่นักเรียนนั่งอ่านหนังสือจนดึก",
      "รู้สึกหมดแรงและเริ่มจะนอนหลับ...",
      "ส้มลูกนี้ปรากฏกายขึ้น",
      '"ทานเพียงลูกเดียว สมาธิจะกลับมา"',
    ],
    ability: "ช่วยให้สมาธิดีขึ้น อ่านหนังสือได้นานขึ้น 30 นาที",
  },
  {
    id: "#026",
    emoji: "🍊",
    color: "yellow",
    nameTH: "ส้มโอสดชื่น",
    nameEN: "Refreshing Pomelo",
    stats: { mind: 35, body: 40, spirit: 40 },
    rarity: "uncommon",
    lore: ["ส้มโอที่สดชื่น", "กินแล้วตื่นขึ้น", '"สดชื่น พร้อมเรียน"'],
    ability: "ตื่นตา ตื่นใจ อ่านหนังสือได้ต่อเนื่อง",
  },
  {
    id: "#027",
    emoji: "🍋",
    color: "yellow",
    nameTH: "มะนาวกระตุ้นพลัง",
    nameEN: "Energy Lemon",
    stats: { mind: 30, body: 35, spirit: 50 },
    rarity: "uncommon",
    lore: ["มะนาวที่กระตุ้นพลัง", "เปรี้ยวแต่ดี", '"กระตุ้นสมองให้ทำงาน"'],
    ability: "กระตุ้นพลัง ทำข้อสอบได้เร็วขึ้น",
  },
  {
    id: "#028",
    emoji: "🍇",
    color: "yellow",
    nameTH: "องุ่นแห่งความจำ",
    nameEN: "Memory Grape",
    stats: { mind: 55, body: 35, spirit: 40 },
    rarity: "uncommon",
    lore: ["องุ่นที่ช่วยจำ", "ทานทีละเม็็ด", '"จำทีละเรื่อง ได้ทุกเรื่อง"'],
    ability: "ช่วยให้จำได้ดีขึ้น จำเนื้อหาได้นาน",
  },
  {
    id: "#029",
    emoji: "🍓",
    color: "yellow",
    nameTH: "สตรอว์เบอร์รี่ใสใส",
    nameEN: "Clarity Strawberry",
    stats: { mind: 60, body: 30, spirit: 50 },
    rarity: "uncommon",
    lore: [
      "สตรอว์เบอร์รี่ที่ใสสะอาด",
      "ช่วยให้ความคิดชัดเจน",
      '"ความใส คือ ความรู้"',
    ],
    ability: "ทำให้ความคิดชัดเจน เข้าใจโจทย์ได้ง่ายขึ้น",
  },
  {
    id: "#030",
    emoji: "🍑",
    color: "yellow",
    nameTH: "ท้อเปิดนำโชค",
    nameEN: "Lucky Peach",
    stats: { mind: 40, body: 35, spirit: 60 },
    rarity: "uncommon",
    lore: ["ลูกท้อที่เปิดออก", "ภายในคือโชค", '"เปิดใจ รับโชค"'],
    ability: "เปิดโอกาสใหม่ โชคดีในการสอบ",
  },
  {
    id: "#031",
    emoji: "🍒",
    color: "yellow",
    nameTH: "เชอร์รี่คู่แห่งความสำเร็จ",
    nameEN: "Success Cherry",
    stats: { mind: 50, body: 40, spirit: 55 },
    rarity: "uncommon",
    lore: [
      "เชอร์รี่สองลูกคู่กัน",
      "เหมือนความสำเร็จที่มาคู่",
      '"สำเร็จคู่ ใช่ดับคู่"',
    ],
    ability: "เพิ่มโอกาสความสำเร็จ ผ่านการสอบได้ดี",
  },
  {
    id: "#032",
    emoji: "🥝",
    color: "yellow",
    nameTH: "เมืองทองแห่งความจำ",
    nameEN: "Golden Kiwi of Memory",
    stats: { mind: 99, body: 95, spirit: 88 },
    rarity: "uncommon",
    lore: [
      "ในตำนานเล่าว่า ผู้ที่ได้กินเมืองทองนี้",
      "จะจำได้ทุกสิ่งที่เคยอ่าน",
      "นักเรียนผู้หนึ่งใช้มาสอบเข้ามหาวิทยาลัย",
      "และได้คะแนนเต็ม... ตั้งแต่นั้นมา",
      "ไม่มีใครเคยเห็นเมืองทองลูกนั้นอีกเลย",
    ],
    ability: "จำได้ทุกสิ่งที่อ่าน ความจำอมตะ นาน 24 ชั่วโมง",
  },
];
